Repository tcz717/SimCivil, pull requests merged in 2019-05, with the labels that each got.

#40 Heartbeat on RpcClient and Timeout on RpcServer
  .editorconfig
  SimCivil.Contract/IConnectionControl.cs
  SimCivil.Gate/Gate.cs
  SimCivil.Gate/GatewayConnectionControl.cs
  SimCivil.IntegrationTest/SimCivil.IntegrationTest.csproj
  SimCivil.IntegrationTest/Testcase/HeartbeatTest.cs
  SimCivil.IntegrationTest/Testcase/MovementTest.cs
  SimCivil.Rpc/RpcClient.cs
  SimCivil.Rpc/RpcInterceptor.cs
  SimCivil.Rpc/RpcRequest.cs
  SimCivil.Rpc/RpcResolver.cs
  SimCivil.Rpc/RpcServer.cs
  SimCivil.Rpc/Session/IRpcSession.cs
  SimCivil.Rpc/SimCivil.Rpc.csproj
  SimCivil.Rpc/Timeout/ClientTimeoutEventArgs.cs
  SimCivil.Rpc/Timeout/ITimeoutDaemon.cs
  SimCivil.Rpc/Timeout/SimpleTimeoutDaemon.cs
  SimCivil.Rpc/UtilHelper.cs
  SimCivil.Test/RpcTest.cs
  SimCivil.Test/SimCivil.Test.csproj
  SimCivil.sln
  SimCivil.sln.DotSettings
Labels: enhancement, network

#52 Modify Inspect API to show detailed data
  SimCivil.Contract/EntityInspection.cs
  SimCivil.Gate/Gate.cs
  SimCivil.Gate/before-deploy.ps1
  SimCivil.Orleans.Grains/Component/BaseGrain.cs
  SimCivil.Orleans.Grains/Component/ControllerGrain.cs
  SimCivil.Orleans.Grains/Component/UnitGrain.cs
  SimCivil.Orleans.Interfaces/IComponent.cs
  SimCivil.Orleans.Server/Program.cs
Labels: enhancement, game

#54 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: doc

#51 Remove locks and use bool for timeout
  SimCivil.IntegrationTest/Testcase/HeartbeatTest.cs
  SimCivil.Rpc/RpcClient.cs
  SimCivil.Rpc/RpcServer.cs
  SimCivil.Rpc/Timeout/ITimeoutDaemon.cs
  SimCivil.Rpc/Timeout/SimpleTimeoutDaemon.cs
  SimCivil.sln.DotSettings
Labels: enhancement, network

#58 Fix #53 Implement missing GetHP
  SimCivil.Gate/OrleansChunkViewSynchronizer.cs
  SimCivil.IntegrationTest/Testcase/MovementTest.cs
  SimCivil.Orleans.Grains/Component/UnitGrain.cs
Labels: bug
