Repository tcz717/SimCivil, pull requests merged in 2019-06, with the labels that each got.

#69 在readme中加入Package说明，移除过期信息
  README.md
Labels: doc

#72 Fix prebuilder task fail and add build option to disable prebuild
  SimCivil.Gate/Dockerfile
  SimCivil.Orleans.Interfaces/SimCivil.Orleans.Interfaces.csproj
  SimCivil.Orleans.Server/Dockerfile
  SimCivil.Tool.PrebuildTasks/extension.csproj
  xunit.bash
Labels: editor

#74 Implement ContainerGrain and PhysicalGrain with tests.
  SimCivil.Orleans.Grains/Component/Item/BuildableGrain.cs
  SimCivil.Orleans.Grains/Component/Item/ContainerGrain.cs
  SimCivil.Orleans.Grains/Component/Item/EquipableGrain.cs
  SimCivil.Orleans.Grains/Component/Item/ItemGrain.cs
  SimCivil.Orleans.Grains/Component/Item/MagicalGrain.cs
  SimCivil.Orleans.Grains/Component/Item/PhysicalGrain.cs
  SimCivil.Orleans.Grains/Component/Item/UsableGrain.cs
  SimCivil.Orleans.Grains/SimCivil.Orleans.Grains.csproj
  SimCivil.Orleans.Interfaces/Component/Item/IContainer.cs
  SimCivil.Orleans.Interfaces/Component/Item/IEquipable.cs
  SimCivil.Orleans.Interfaces/Component/Item/IItem.cs
  SimCivil.Orleans.Interfaces/Component/Item/IMagical.cs
  SimCivil.Orleans.Interfaces/Component/Item/IPhysical.cs
  SimCivil.Orleans.Interfaces/Component/Item/Result.cs
  SimCivil.Orleans.Interfaces/Component/Item/State/ContainerState.cs
  SimCivil.Orleans.Interfaces/Component/Item/State/EquipableState.cs
  SimCivil.Orleans.Interfaces/Component/Item/State/MagicalState.cs
  SimCivil.Orleans.Interfaces/Item/AssemblyPart.cs
  SimCivil.Orleans.Interfaces/Item/SinglePart.cs
  SimCivil.Orleans.Interfaces/SimCivil.Orleans.Interfaces.csproj
  SimCivil.Test/Orleans/ItemTest.cs
  SimCivil.Tool.PrebuildTasks/BuilderDispatcher.cs
  SimCivil.Tool.PrebuildTasks/FileModifier.cs
  SimCivil.Tool.PrebuildTasks/FileUtils.cs
  SimCivil.Tool.PrebuildTasks/Prebuilders/GrainPrebuilder.cs
  SimCivil.Tool.PrebuildTasks/Prebuilders/InterfacePrebuilder.cs
  SimCivil.Tool.PrebuildTasks/Program.cs
  SimCivil.Tool.PrebuildTasks/extension.csproj
  SimCivil.sln
Labels: feature, game
